### ISSUE TITLE
Average_pixel returns error when importing python modules

### ISSUE THREAD

**Issue by weiren2** [lsst-camera-visualization/backend#18]
Average_pixel fails to import scipy generic filter. Previously it worked fine. I suspect that it needs extra library due to newer version of scipy/numpy.

**Comment by weiren2** [comment]
Or maybe I am the only one who experienced this error (seems like a dependency issue):confused:

> Error: edu.caltech.ipac.firefly.server.query.DataAccessException: Unable to get data from external task: Failed to obtain data. Traceback (most recent call last): File "/home/wei/lsst/lsst_firefly/backend/dispatcher.py", line 6, in <module> from tasks import execute_task File "/home/wei/lsst/lsst_firefly/backend/tasks.py", line 1, in <module> from task_scripts.averagePixel import task as task_average_pixel File "/home/wei/lsst/lsst_firefly/backend/task_scripts/averagePixel.py", line 4, in <module> from scipy.ndimage.filters import generic_filter as gf File "/home/wei/miniconda3/lib/python3.5/site-packages/scipy/ndimage/__init__.py", line 161, in <module> from .filters import * File "/home/wei/miniconda3/lib/python3.5/site-packages/scipy/ndimage/filters.py", line 37, in <module> from scipy.misc import doccer File "/home/wei/miniconda3/lib/python3.5/site-packages/scipy/misc/__init__.py", line 51, in <module> from scipy.special import comb, factorial, factorial2, factorialk File "/home/wei/miniconda3/lib/python3.5/site-packages/scipy/special/__init__.py", line 636, in <module> from ._ufuncs import * ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory

**Comment by weiren2** [comment]
I managed to fix the error by a clean install and update of python (I'm using Miniconda).

**Comment by jonthaler** [comment]
Great!

Did you ever see this error (that Yutong saw) on Friday:
* cmd.js:351 Uncaught ReferenceError: parse_region is not defined(…)\

Jon
