### ISSUE TITLE
Handle circular regions

### ISSUE THREAD

**Issue by jbpagliuco** [lsst-camera-visualization/backend#2]
In addition to rectangular regions, we need to be able to handle calculations for circle regions (a center point and a radius)

**Comment by weiren2** [comment]
I'm thinking of using circular mask and filters to calculate the mean value. I hope it will work more efficiently if we are dealing with large data of 2D matrix. We can compare the performance with the generic method.

**Comment by jonthaler** [comment]
The LSST stack may have a function that performs the algorithm we want:
- Scan over a bunch of pixels and perform a function (that you pass it) on the ones that satisfy a criterion (that you pass it).

Jon

**Comment by weiren2** [comment]
Circular region is now supported in `average_pixel` function.
